<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ICE_LogApplication.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace UVLogAppServer
{
    global $UVLogAppServer__t_LogAppServer;
    global $UVLogAppServer__t_LogAppServerPrx;

    class LogAppServerPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::UVLogAppServer::LogAppServer', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::UVLogAppServer::LogAppServer', $facet);
        }

        public static function ice_staticId()
        {
            return '::UVLogAppServer::LogAppServer';
        }
    }
    $UVLogAppServer__t_LogAppServer = IcePHP_defineClass('::UVLogAppServer::LogAppServer', '\\UVLogAppServer\\LogAppServer', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $UVLogAppServer__t_LogAppServerPrx = IcePHP_defineProxy('::UVLogAppServer::LogAppServer', $Ice__t_ObjectPrx, null);

    global $IcePHP__t_bool;
    global $IcePHP__t_string;
    IcePHP_defineOperation($UVLogAppServer__t_LogAppServerPrx, 'Ping', 0, 0, 0, null, null, array($IcePHP__t_bool), null);
    IcePHP_defineOperation($UVLogAppServer__t_LogAppServerPrx, 'Shutdown', 0, 0, 0, null, null, null, null);
    IcePHP_defineOperation($UVLogAppServer__t_LogAppServerPrx, 'insertItem', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_string), array($IcePHP__t_string), array($IcePHP__t_string)), null, null, null);
}
?>
