<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ICE_ServerApplication.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace UVServerAppServer
{
    global $UVServerAppServer__t_tyStringSequence;

    if(!isset($UVServerAppServer__t_tyStringSequence))
    {
        global $IcePHP__t_string;
        $UVServerAppServer__t_tyStringSequence = IcePHP_defineSequence('::UVServerAppServer::tyStringSequence', $IcePHP__t_string);
    }
}

namespace UVServerAppServer
{
    global $UVServerAppServer__t_ServerAppServer;
    global $UVServerAppServer__t_ServerAppServerPrx;

    class ServerAppServerPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::UVServerAppServer::ServerAppServer', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::UVServerAppServer::ServerAppServer', $facet);
        }

        public static function ice_staticId()
        {
            return '::UVServerAppServer::ServerAppServer';
        }
    }
    $UVServerAppServer__t_ServerAppServer = IcePHP_defineClass('::UVServerAppServer::ServerAppServer', '\\UVServerAppServer\\ServerAppServer', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $UVServerAppServer__t_ServerAppServerPrx = IcePHP_defineProxy('::UVServerAppServer::ServerAppServer', $Ice__t_ObjectPrx, null);

    global $IcePHP__t_bool;
    global $IcePHP__t_string;
    global $UVServerAppServer__t_tyStringSequence;
    IcePHP_defineOperation($UVServerAppServer__t_ServerAppServerPrx, 'Ping', 0, 0, 0, null, null, array($IcePHP__t_bool), null);
    IcePHP_defineOperation($UVServerAppServer__t_ServerAppServerPrx, 'Shutdown', 0, 0, 0, null, null, null, null);
    IcePHP_defineOperation($UVServerAppServer__t_ServerAppServerPrx, 'insertIntoTableDatabase', 0, 0, 0, array(array($IcePHP__t_string), array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence)), array(array($IcePHP__t_string)), array($IcePHP__t_bool), null);
    IcePHP_defineOperation($UVServerAppServer__t_ServerAppServerPrx, 'updateIntoTableDatabase', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_string), array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence)), array(array($IcePHP__t_string)), array($IcePHP__t_bool), null);
    IcePHP_defineOperation($UVServerAppServer__t_ServerAppServerPrx, 'deleteIntoTableDatabase', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_string)), array(array($IcePHP__t_string)), array($IcePHP__t_bool), null);
    IcePHP_defineOperation($UVServerAppServer__t_ServerAppServerPrx, 'getFromTableDatabaseGeneral', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_string), array($IcePHP__t_string)), array(array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence), array($IcePHP__t_string)), array($IcePHP__t_bool), null);
    IcePHP_defineOperation($UVServerAppServer__t_ServerAppServerPrx, 'getFromTableDatbaseByProperty', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_string), array($IcePHP__t_string), array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence)), array(array($UVServerAppServer__t_tyStringSequence), array($IcePHP__t_string)), array($IcePHP__t_bool), null);
    IcePHP_defineOperation($UVServerAppServer__t_ServerAppServerPrx, 'getFromTableDatabaseById', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_string), array($UVServerAppServer__t_tyStringSequence)), array(array($UVServerAppServer__t_tyStringSequence), array($IcePHP__t_string)), array($IcePHP__t_bool), null);
    IcePHP_defineOperation($UVServerAppServer__t_ServerAppServerPrx, 'getAllTablesFromDatabase', 0, 0, 0, null, array(array($UVServerAppServer__t_tyStringSequence), array($IcePHP__t_string)), array($IcePHP__t_bool), null);
    IcePHP_defineOperation($UVServerAppServer__t_ServerAppServerPrx, 'getAllMethodsFromTable', 0, 0, 0, array(array($IcePHP__t_string)), array(array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence), array($IcePHP__t_string)), array($IcePHP__t_bool), null);
    IcePHP_defineOperation($UVServerAppServer__t_ServerAppServerPrx, 'getAllPropertiesFromTable', 0, 0, 0, array(array($IcePHP__t_string)), array(array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence), array($UVServerAppServer__t_tyStringSequence), array($IcePHP__t_string)), array($IcePHP__t_bool), null);
    IcePHP_defineOperation($UVServerAppServer__t_ServerAppServerPrx, 'giveWorkstationClientInfo', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_string), array($IcePHP__t_string), array($IcePHP__t_string)), array(array($IcePHP__t_string)), array($IcePHP__t_bool), null);
}
?>
