//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ICE_ServerApplication.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <ICE_ServerApplication.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 10
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_UVServerAppServer_ServerAppServer_ids[2] =
{
    "::Ice::Object",
    "::UVServerAppServer::ServerAppServer"
};
const ::std::string iceC_UVServerAppServer_ServerAppServer_ops[] =
{
    "Ping",
    "Shutdown",
    "deleteIntoTableDatabase",
    "getAllMethodsFromTable",
    "getAllPropertiesFromTable",
    "getAllTablesFromDatabase",
    "getFromTableDatabaseById",
    "getFromTableDatabaseGeneral",
    "getFromTableDatbaseByProperty",
    "getFromTableDatbaseByPropertyRepresentProp",
    "giveWorkstationClientInfo",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "insertIntoTableDatabase",
    "updateIntoTableDatabase"
};
const ::std::string iceC_UVServerAppServer_ServerAppServer_Ping_name = "Ping";
const ::std::string iceC_UVServerAppServer_ServerAppServer_Shutdown_name = "Shutdown";
const ::std::string iceC_UVServerAppServer_ServerAppServer_insertIntoTableDatabase_name = "insertIntoTableDatabase";
const ::std::string iceC_UVServerAppServer_ServerAppServer_updateIntoTableDatabase_name = "updateIntoTableDatabase";
const ::std::string iceC_UVServerAppServer_ServerAppServer_deleteIntoTableDatabase_name = "deleteIntoTableDatabase";
const ::std::string iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseGeneral_name = "getFromTableDatabaseGeneral";
const ::std::string iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByProperty_name = "getFromTableDatbaseByProperty";
const ::std::string iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByPropertyRepresentProp_name = "getFromTableDatbaseByPropertyRepresentProp";
const ::std::string iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseById_name = "getFromTableDatabaseById";
const ::std::string iceC_UVServerAppServer_ServerAppServer_getAllTablesFromDatabase_name = "getAllTablesFromDatabase";
const ::std::string iceC_UVServerAppServer_ServerAppServer_getAllMethodsFromTable_name = "getAllMethodsFromTable";
const ::std::string iceC_UVServerAppServer_ServerAppServer_getAllPropertiesFromTable_name = "getAllPropertiesFromTable";
const ::std::string iceC_UVServerAppServer_ServerAppServer_giveWorkstationClientInfo_name = "giveWorkstationClientInfo";

}

bool
UVServerAppServer::ServerAppServer::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_UVServerAppServer_ServerAppServer_ids, iceC_UVServerAppServer_ServerAppServer_ids + 2, s);
}

::std::vector<::std::string>
UVServerAppServer::ServerAppServer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_UVServerAppServer_ServerAppServer_ids[0], &iceC_UVServerAppServer_ServerAppServer_ids[2]);
}

::std::string
UVServerAppServer::ServerAppServer::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
UVServerAppServer::ServerAppServer::ice_staticId()
{
    static const ::std::string typeId = "::UVServerAppServer::ServerAppServer";
    return typeId;
}

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_Ping(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->Ping(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_Shutdown(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->Shutdown(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_insertIntoTableDatabase(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_paTableName;
    tyStringSequence iceP_paColumns;
    tyStringSequence iceP_paValue;
    tyStringSequence iceP_paTypeValue;
    istr->readAll(iceP_paTableName, iceP_paColumns, iceP_paValue, iceP_paTypeValue);
    inS.endReadParams();
    ::std::string iceP_paReturnMessage;
    bool ret = this->insertIntoTableDatabase(::std::move(iceP_paTableName), ::std::move(iceP_paColumns), ::std::move(iceP_paValue), ::std::move(iceP_paTypeValue), iceP_paReturnMessage, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_paReturnMessage, ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_updateIntoTableDatabase(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_paTableName;
    ::std::string iceP_paId;
    tyStringSequence iceP_paColumns;
    tyStringSequence iceP_paValue;
    tyStringSequence iceP_paTypeValue;
    istr->readAll(iceP_paTableName, iceP_paId, iceP_paColumns, iceP_paValue, iceP_paTypeValue);
    inS.endReadParams();
    ::std::string iceP_paReturnMessage;
    bool ret = this->updateIntoTableDatabase(::std::move(iceP_paTableName), ::std::move(iceP_paId), ::std::move(iceP_paColumns), ::std::move(iceP_paValue), ::std::move(iceP_paTypeValue), iceP_paReturnMessage, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_paReturnMessage, ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_deleteIntoTableDatabase(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_paTableName;
    ::std::string iceP_paId;
    istr->readAll(iceP_paTableName, iceP_paId);
    inS.endReadParams();
    ::std::string iceP_paReturnMessage;
    bool ret = this->deleteIntoTableDatabase(::std::move(iceP_paTableName), ::std::move(iceP_paId), iceP_paReturnMessage, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_paReturnMessage, ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_getFromTableDatabaseGeneral(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_paTableName;
    ::std::string iceP_paStartValue;
    ::std::string iceP_paMaxValue;
    istr->readAll(iceP_paTableName, iceP_paStartValue, iceP_paMaxValue);
    inS.endReadParams();
    tyStringSequence iceP_paReturnId;
    tyStringSequence iceP_paReturnName;
    ::std::string iceP_paMessage;
    bool ret = this->getFromTableDatabaseGeneral(::std::move(iceP_paTableName), ::std::move(iceP_paStartValue), ::std::move(iceP_paMaxValue), iceP_paReturnId, iceP_paReturnName, iceP_paMessage, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_paReturnId, iceP_paReturnName, iceP_paMessage, ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_getFromTableDatbaseByProperty(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_paTableName;
    ::std::string iceP_paStartValue;
    ::std::string iceP_paMaxValue;
    tyStringSequence iceP_paProperties;
    tyStringSequence iceP_paValue;
    tyStringSequence iceP_paTypeValue;
    tyStringSequence iceP_paLogExp;
    istr->readAll(iceP_paTableName, iceP_paStartValue, iceP_paMaxValue, iceP_paProperties, iceP_paValue, iceP_paTypeValue, iceP_paLogExp);
    inS.endReadParams();
    tyStringSequence iceP_paReturnId;
    ::std::string iceP_paReturnMessage;
    bool ret = this->getFromTableDatbaseByProperty(::std::move(iceP_paTableName), ::std::move(iceP_paStartValue), ::std::move(iceP_paMaxValue), ::std::move(iceP_paProperties), ::std::move(iceP_paValue), ::std::move(iceP_paTypeValue), ::std::move(iceP_paLogExp), iceP_paReturnId, iceP_paReturnMessage, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_paReturnId, iceP_paReturnMessage, ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_getFromTableDatbaseByPropertyRepresentProp(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_paTableName;
    ::std::string iceP_paStartValue;
    ::std::string iceP_paMaxValue;
    tyStringSequence iceP_paProperties;
    tyStringSequence iceP_paValue;
    tyStringSequence iceP_paTypeValue;
    tyStringSequence iceP_paLogExp;
    istr->readAll(iceP_paTableName, iceP_paStartValue, iceP_paMaxValue, iceP_paProperties, iceP_paValue, iceP_paTypeValue, iceP_paLogExp);
    inS.endReadParams();
    tyStringSequence iceP_paPropertiesReturn;
    tyStringSequence iceP_paValuesReturn;
    ::std::string iceP_paReturnMessage;
    bool ret = this->getFromTableDatbaseByPropertyRepresentProp(::std::move(iceP_paTableName), ::std::move(iceP_paStartValue), ::std::move(iceP_paMaxValue), ::std::move(iceP_paProperties), ::std::move(iceP_paValue), ::std::move(iceP_paTypeValue), ::std::move(iceP_paLogExp), iceP_paPropertiesReturn, iceP_paValuesReturn, iceP_paReturnMessage, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_paPropertiesReturn, iceP_paValuesReturn, iceP_paReturnMessage, ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_getFromTableDatabaseById(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_paTableName;
    ::std::string iceP_paId;
    tyStringSequence iceP_paProperties;
    istr->readAll(iceP_paTableName, iceP_paId, iceP_paProperties);
    inS.endReadParams();
    tyStringSequence iceP_paReturnValue;
    ::std::string iceP_paReturnMessage;
    bool ret = this->getFromTableDatabaseById(::std::move(iceP_paTableName), ::std::move(iceP_paId), ::std::move(iceP_paProperties), iceP_paReturnValue, iceP_paReturnMessage, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_paReturnValue, iceP_paReturnMessage, ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_getAllTablesFromDatabase(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    tyStringSequence iceP_paTables;
    ::std::string iceP_paReturnMessage;
    bool ret = this->getAllTablesFromDatabase(iceP_paTables, iceP_paReturnMessage, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_paTables, iceP_paReturnMessage, ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_getAllMethodsFromTable(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_paTable;
    istr->readAll(iceP_paTable);
    inS.endReadParams();
    tyStringSequence iceP_paMethodName;
    tyStringSequence iceP_paAlias;
    tyStringSequence iceP_paSource;
    tyStringSequence iceP_paSourceName;
    tyStringSequence iceP_paReturnType;
    ::std::string iceP_paReturnMessage;
    bool ret = this->getAllMethodsFromTable(::std::move(iceP_paTable), iceP_paMethodName, iceP_paAlias, iceP_paSource, iceP_paSourceName, iceP_paReturnType, iceP_paReturnMessage, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_paMethodName, iceP_paAlias, iceP_paSource, iceP_paSourceName, iceP_paReturnType, iceP_paReturnMessage, ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_getAllPropertiesFromTable(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_paTable;
    istr->readAll(iceP_paTable);
    inS.endReadParams();
    tyStringSequence iceP_paPropertyName;
    tyStringSequence iceP_paAlias;
    tyStringSequence iceP_paType;
    tyStringSequence iceP_paExtra;
    tyStringSequence iceP_paReference;
    ::std::string iceP_paReturnMessage;
    bool ret = this->getAllPropertiesFromTable(::std::move(iceP_paTable), iceP_paPropertyName, iceP_paAlias, iceP_paType, iceP_paExtra, iceP_paReference, iceP_paReturnMessage, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_paPropertyName, iceP_paAlias, iceP_paType, iceP_paExtra, iceP_paReference, iceP_paReturnMessage, ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_giveWorkstationClientInfo(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_paWorkstationName;
    ::std::string iceP_paPercentageMemUsage;
    ::std::string iceP_paPercentageDiskUsage;
    ::std::string iceP_paPercentageCpuUsage;
    istr->readAll(iceP_paWorkstationName, iceP_paPercentageMemUsage, iceP_paPercentageDiskUsage, iceP_paPercentageCpuUsage);
    inS.endReadParams();
    ::std::string iceP_paReturnMessage;
    bool ret = this->giveWorkstationClientInfo(::std::move(iceP_paWorkstationName), ::std::move(iceP_paPercentageMemUsage), ::std::move(iceP_paPercentageDiskUsage), ::std::move(iceP_paPercentageCpuUsage), iceP_paReturnMessage, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(iceP_paReturnMessage, ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_UVServerAppServer_ServerAppServer_ops, iceC_UVServerAppServer_ServerAppServer_ops + 17, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_UVServerAppServer_ServerAppServer_ops)
    {
        case 0:
        {
            return _iceD_Ping(in, current);
        }
        case 1:
        {
            return _iceD_Shutdown(in, current);
        }
        case 2:
        {
            return _iceD_deleteIntoTableDatabase(in, current);
        }
        case 3:
        {
            return _iceD_getAllMethodsFromTable(in, current);
        }
        case 4:
        {
            return _iceD_getAllPropertiesFromTable(in, current);
        }
        case 5:
        {
            return _iceD_getAllTablesFromDatabase(in, current);
        }
        case 6:
        {
            return _iceD_getFromTableDatabaseById(in, current);
        }
        case 7:
        {
            return _iceD_getFromTableDatabaseGeneral(in, current);
        }
        case 8:
        {
            return _iceD_getFromTableDatbaseByProperty(in, current);
        }
        case 9:
        {
            return _iceD_getFromTableDatbaseByPropertyRepresentProp(in, current);
        }
        case 10:
        {
            return _iceD_giveWorkstationClientInfo(in, current);
        }
        case 11:
        {
            return _iceD_ice_id(in, current);
        }
        case 12:
        {
            return _iceD_ice_ids(in, current);
        }
        case 13:
        {
            return _iceD_ice_isA(in, current);
        }
        case 14:
        {
            return _iceD_ice_ping(in, current);
        }
        case 15:
        {
            return _iceD_insertIntoTableDatabase(in, current);
        }
        case 16:
        {
            return _iceD_updateIntoTableDatabase(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
UVServerAppServer::ServerAppServerPrx::_iceI_Ping(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_Ping_name);
    outAsync->invoke(iceC_UVServerAppServer_ServerAppServer_Ping_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
UVServerAppServer::ServerAppServerPrx::_iceI_Shutdown(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_UVServerAppServer_ServerAppServer_Shutdown_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
UVServerAppServer::ServerAppServerPrx::_iceI_insertIntoTableDatabase(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<ServerAppServer::InsertIntoTableDatabaseResult>>& outAsync, const ::std::string& iceP_paTableName, const tyStringSequence& iceP_paColumns, const tyStringSequence& iceP_paValue, const tyStringSequence& iceP_paTypeValue, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_insertIntoTableDatabase_name);
    outAsync->invoke(iceC_UVServerAppServer_ServerAppServer_insertIntoTableDatabase_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_paTableName, iceP_paColumns, iceP_paValue, iceP_paTypeValue);
        },
        nullptr,
        [](::Ice::InputStream* istr)
        {
            ServerAppServer::InsertIntoTableDatabaseResult v;
            istr->readAll(v.paReturnMessage, v.returnValue);
            return v;
        });
}
/// \endcond

/// \cond INTERNAL
void
UVServerAppServer::ServerAppServerPrx::_iceI_updateIntoTableDatabase(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<ServerAppServer::UpdateIntoTableDatabaseResult>>& outAsync, const ::std::string& iceP_paTableName, const ::std::string& iceP_paId, const tyStringSequence& iceP_paColumns, const tyStringSequence& iceP_paValue, const tyStringSequence& iceP_paTypeValue, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_updateIntoTableDatabase_name);
    outAsync->invoke(iceC_UVServerAppServer_ServerAppServer_updateIntoTableDatabase_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_paTableName, iceP_paId, iceP_paColumns, iceP_paValue, iceP_paTypeValue);
        },
        nullptr,
        [](::Ice::InputStream* istr)
        {
            ServerAppServer::UpdateIntoTableDatabaseResult v;
            istr->readAll(v.paReturnMessage, v.returnValue);
            return v;
        });
}
/// \endcond

/// \cond INTERNAL
void
UVServerAppServer::ServerAppServerPrx::_iceI_deleteIntoTableDatabase(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<ServerAppServer::DeleteIntoTableDatabaseResult>>& outAsync, const ::std::string& iceP_paTableName, const ::std::string& iceP_paId, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_deleteIntoTableDatabase_name);
    outAsync->invoke(iceC_UVServerAppServer_ServerAppServer_deleteIntoTableDatabase_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_paTableName, iceP_paId);
        },
        nullptr,
        [](::Ice::InputStream* istr)
        {
            ServerAppServer::DeleteIntoTableDatabaseResult v;
            istr->readAll(v.paReturnMessage, v.returnValue);
            return v;
        });
}
/// \endcond

/// \cond INTERNAL
void
UVServerAppServer::ServerAppServerPrx::_iceI_getFromTableDatabaseGeneral(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<ServerAppServer::GetFromTableDatabaseGeneralResult>>& outAsync, const ::std::string& iceP_paTableName, const ::std::string& iceP_paStartValue, const ::std::string& iceP_paMaxValue, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseGeneral_name);
    outAsync->invoke(iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseGeneral_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_paTableName, iceP_paStartValue, iceP_paMaxValue);
        },
        nullptr,
        [](::Ice::InputStream* istr)
        {
            ServerAppServer::GetFromTableDatabaseGeneralResult v;
            istr->readAll(v.paReturnId, v.paReturnName, v.paMessage, v.returnValue);
            return v;
        });
}
/// \endcond

/// \cond INTERNAL
void
UVServerAppServer::ServerAppServerPrx::_iceI_getFromTableDatbaseByProperty(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<ServerAppServer::GetFromTableDatbaseByPropertyResult>>& outAsync, const ::std::string& iceP_paTableName, const ::std::string& iceP_paStartValue, const ::std::string& iceP_paMaxValue, const tyStringSequence& iceP_paProperties, const tyStringSequence& iceP_paValue, const tyStringSequence& iceP_paTypeValue, const tyStringSequence& iceP_paLogExp, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByProperty_name);
    outAsync->invoke(iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByProperty_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_paTableName, iceP_paStartValue, iceP_paMaxValue, iceP_paProperties, iceP_paValue, iceP_paTypeValue, iceP_paLogExp);
        },
        nullptr,
        [](::Ice::InputStream* istr)
        {
            ServerAppServer::GetFromTableDatbaseByPropertyResult v;
            istr->readAll(v.paReturnId, v.paReturnMessage, v.returnValue);
            return v;
        });
}
/// \endcond

/// \cond INTERNAL
void
UVServerAppServer::ServerAppServerPrx::_iceI_getFromTableDatbaseByPropertyRepresentProp(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<ServerAppServer::GetFromTableDatbaseByPropertyRepresentPropResult>>& outAsync, const ::std::string& iceP_paTableName, const ::std::string& iceP_paStartValue, const ::std::string& iceP_paMaxValue, const tyStringSequence& iceP_paProperties, const tyStringSequence& iceP_paValue, const tyStringSequence& iceP_paTypeValue, const tyStringSequence& iceP_paLogExp, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByPropertyRepresentProp_name);
    outAsync->invoke(iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByPropertyRepresentProp_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_paTableName, iceP_paStartValue, iceP_paMaxValue, iceP_paProperties, iceP_paValue, iceP_paTypeValue, iceP_paLogExp);
        },
        nullptr,
        [](::Ice::InputStream* istr)
        {
            ServerAppServer::GetFromTableDatbaseByPropertyRepresentPropResult v;
            istr->readAll(v.paPropertiesReturn, v.paValuesReturn, v.paReturnMessage, v.returnValue);
            return v;
        });
}
/// \endcond

/// \cond INTERNAL
void
UVServerAppServer::ServerAppServerPrx::_iceI_getFromTableDatabaseById(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<ServerAppServer::GetFromTableDatabaseByIdResult>>& outAsync, const ::std::string& iceP_paTableName, const ::std::string& iceP_paId, const tyStringSequence& iceP_paProperties, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseById_name);
    outAsync->invoke(iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseById_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_paTableName, iceP_paId, iceP_paProperties);
        },
        nullptr,
        [](::Ice::InputStream* istr)
        {
            ServerAppServer::GetFromTableDatabaseByIdResult v;
            istr->readAll(v.paReturnValue, v.paReturnMessage, v.returnValue);
            return v;
        });
}
/// \endcond

/// \cond INTERNAL
void
UVServerAppServer::ServerAppServerPrx::_iceI_getAllTablesFromDatabase(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<ServerAppServer::GetAllTablesFromDatabaseResult>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_getAllTablesFromDatabase_name);
    outAsync->invoke(iceC_UVServerAppServer_ServerAppServer_getAllTablesFromDatabase_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr,
        [](::Ice::InputStream* istr)
        {
            ServerAppServer::GetAllTablesFromDatabaseResult v;
            istr->readAll(v.paTables, v.paReturnMessage, v.returnValue);
            return v;
        });
}
/// \endcond

/// \cond INTERNAL
void
UVServerAppServer::ServerAppServerPrx::_iceI_getAllMethodsFromTable(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<ServerAppServer::GetAllMethodsFromTableResult>>& outAsync, const ::std::string& iceP_paTable, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_getAllMethodsFromTable_name);
    outAsync->invoke(iceC_UVServerAppServer_ServerAppServer_getAllMethodsFromTable_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_paTable);
        },
        nullptr,
        [](::Ice::InputStream* istr)
        {
            ServerAppServer::GetAllMethodsFromTableResult v;
            istr->readAll(v.paMethodName, v.paAlias, v.paSource, v.paSourceName, v.paReturnType, v.paReturnMessage, v.returnValue);
            return v;
        });
}
/// \endcond

/// \cond INTERNAL
void
UVServerAppServer::ServerAppServerPrx::_iceI_getAllPropertiesFromTable(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<ServerAppServer::GetAllPropertiesFromTableResult>>& outAsync, const ::std::string& iceP_paTable, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_getAllPropertiesFromTable_name);
    outAsync->invoke(iceC_UVServerAppServer_ServerAppServer_getAllPropertiesFromTable_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_paTable);
        },
        nullptr,
        [](::Ice::InputStream* istr)
        {
            ServerAppServer::GetAllPropertiesFromTableResult v;
            istr->readAll(v.paPropertyName, v.paAlias, v.paType, v.paExtra, v.paReference, v.paReturnMessage, v.returnValue);
            return v;
        });
}
/// \endcond

/// \cond INTERNAL
void
UVServerAppServer::ServerAppServerPrx::_iceI_giveWorkstationClientInfo(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<ServerAppServer::GiveWorkstationClientInfoResult>>& outAsync, const ::std::string& iceP_paWorkstationName, const ::std::string& iceP_paPercentageMemUsage, const ::std::string& iceP_paPercentageDiskUsage, const ::std::string& iceP_paPercentageCpuUsage, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_giveWorkstationClientInfo_name);
    outAsync->invoke(iceC_UVServerAppServer_ServerAppServer_giveWorkstationClientInfo_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_paWorkstationName, iceP_paPercentageMemUsage, iceP_paPercentageDiskUsage, iceP_paPercentageCpuUsage);
        },
        nullptr,
        [](::Ice::InputStream* istr)
        {
            ServerAppServer::GiveWorkstationClientInfoResult v;
            istr->readAll(v.paReturnMessage, v.returnValue);
            return v;
        });
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
UVServerAppServer::ServerAppServerPrx::_newInstance() const
{
    return ::IceInternal::createProxy<ServerAppServerPrx>();
}
/// \endcond

const ::std::string&
UVServerAppServer::ServerAppServerPrx::ice_staticId()
{
    return ServerAppServer::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_UVServerAppServer_ServerAppServer_Ping_name = "Ping";

const ::std::string iceC_UVServerAppServer_ServerAppServer_Shutdown_name = "Shutdown";

const ::std::string iceC_UVServerAppServer_ServerAppServer_insertIntoTableDatabase_name = "insertIntoTableDatabase";

const ::std::string iceC_UVServerAppServer_ServerAppServer_updateIntoTableDatabase_name = "updateIntoTableDatabase";

const ::std::string iceC_UVServerAppServer_ServerAppServer_deleteIntoTableDatabase_name = "deleteIntoTableDatabase";

const ::std::string iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseGeneral_name = "getFromTableDatabaseGeneral";

const ::std::string iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByProperty_name = "getFromTableDatbaseByProperty";

const ::std::string iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByPropertyRepresentProp_name = "getFromTableDatbaseByPropertyRepresentProp";

const ::std::string iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseById_name = "getFromTableDatabaseById";

const ::std::string iceC_UVServerAppServer_ServerAppServer_getAllTablesFromDatabase_name = "getAllTablesFromDatabase";

const ::std::string iceC_UVServerAppServer_ServerAppServer_getAllMethodsFromTable_name = "getAllMethodsFromTable";

const ::std::string iceC_UVServerAppServer_ServerAppServer_getAllPropertiesFromTable_name = "getAllPropertiesFromTable";

const ::std::string iceC_UVServerAppServer_ServerAppServer_giveWorkstationClientInfo_name = "giveWorkstationClientInfo";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::UVServerAppServer::upCast(ServerAppServer* p) { return p; }

void
::IceProxy::UVServerAppServer::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ServerAppServer>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ServerAppServer;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::UVServerAppServer::ServerAppServer::_iceI_begin_Ping(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_Ping_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVServerAppServer_ServerAppServer_Ping_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVServerAppServer_ServerAppServer_Ping_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_UVServerAppServer_ServerAppServer_Ping_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::UVServerAppServer::ServerAppServer::end_Ping(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_Ping_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::UVServerAppServer::ServerAppServer::_iceI_begin_Shutdown(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVServerAppServer_ServerAppServer_Shutdown_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVServerAppServer_ServerAppServer_Shutdown_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_UVServerAppServer_ServerAppServer_Shutdown_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::UVServerAppServer::ServerAppServer::end_Shutdown(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_UVServerAppServer_ServerAppServer_Shutdown_name);
}

::Ice::AsyncResultPtr
IceProxy::UVServerAppServer::ServerAppServer::_iceI_begin_insertIntoTableDatabase(const ::std::string& iceP_paTableName, const ::UVServerAppServer::tyStringSequence& iceP_paColumns, const ::UVServerAppServer::tyStringSequence& iceP_paValue, const ::UVServerAppServer::tyStringSequence& iceP_paTypeValue, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_insertIntoTableDatabase_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVServerAppServer_ServerAppServer_insertIntoTableDatabase_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVServerAppServer_ServerAppServer_insertIntoTableDatabase_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_paTableName);
        ostr->write(iceP_paColumns);
        ostr->write(iceP_paValue);
        ostr->write(iceP_paTypeValue);
        result->endWriteParams();
        result->invoke(iceC_UVServerAppServer_ServerAppServer_insertIntoTableDatabase_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::UVServerAppServer::ServerAppServer::end_insertIntoTableDatabase(::std::string& iceP_paReturnMessage, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_insertIntoTableDatabase_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

void IceProxy::UVServerAppServer::ServerAppServer::_iceI_end_insertIntoTableDatabase(::std::string& iceP_paReturnMessage, bool& ret, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_insertIntoTableDatabase_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::UVServerAppServer::ServerAppServer::_iceI_begin_updateIntoTableDatabase(const ::std::string& iceP_paTableName, const ::std::string& iceP_paId, const ::UVServerAppServer::tyStringSequence& iceP_paColumns, const ::UVServerAppServer::tyStringSequence& iceP_paValue, const ::UVServerAppServer::tyStringSequence& iceP_paTypeValue, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_updateIntoTableDatabase_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVServerAppServer_ServerAppServer_updateIntoTableDatabase_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVServerAppServer_ServerAppServer_updateIntoTableDatabase_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_paTableName);
        ostr->write(iceP_paId);
        ostr->write(iceP_paColumns);
        ostr->write(iceP_paValue);
        ostr->write(iceP_paTypeValue);
        result->endWriteParams();
        result->invoke(iceC_UVServerAppServer_ServerAppServer_updateIntoTableDatabase_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::UVServerAppServer::ServerAppServer::end_updateIntoTableDatabase(::std::string& iceP_paReturnMessage, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_updateIntoTableDatabase_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

void IceProxy::UVServerAppServer::ServerAppServer::_iceI_end_updateIntoTableDatabase(::std::string& iceP_paReturnMessage, bool& ret, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_updateIntoTableDatabase_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::UVServerAppServer::ServerAppServer::_iceI_begin_deleteIntoTableDatabase(const ::std::string& iceP_paTableName, const ::std::string& iceP_paId, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_deleteIntoTableDatabase_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVServerAppServer_ServerAppServer_deleteIntoTableDatabase_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVServerAppServer_ServerAppServer_deleteIntoTableDatabase_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_paTableName);
        ostr->write(iceP_paId);
        result->endWriteParams();
        result->invoke(iceC_UVServerAppServer_ServerAppServer_deleteIntoTableDatabase_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::UVServerAppServer::ServerAppServer::end_deleteIntoTableDatabase(::std::string& iceP_paReturnMessage, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_deleteIntoTableDatabase_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

void IceProxy::UVServerAppServer::ServerAppServer::_iceI_end_deleteIntoTableDatabase(::std::string& iceP_paReturnMessage, bool& ret, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_deleteIntoTableDatabase_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::UVServerAppServer::ServerAppServer::_iceI_begin_getFromTableDatabaseGeneral(const ::std::string& iceP_paTableName, const ::std::string& iceP_paStartValue, const ::std::string& iceP_paMaxValue, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseGeneral_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseGeneral_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseGeneral_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_paTableName);
        ostr->write(iceP_paStartValue);
        ostr->write(iceP_paMaxValue);
        result->endWriteParams();
        result->invoke(iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseGeneral_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::UVServerAppServer::ServerAppServer::end_getFromTableDatabaseGeneral(::UVServerAppServer::tyStringSequence& iceP_paReturnId, ::UVServerAppServer::tyStringSequence& iceP_paReturnName, ::std::string& iceP_paMessage, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseGeneral_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paReturnId);
    istr->read(iceP_paReturnName);
    istr->read(iceP_paMessage);
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

void IceProxy::UVServerAppServer::ServerAppServer::_iceI_end_getFromTableDatabaseGeneral(::UVServerAppServer::tyStringSequence& iceP_paReturnId, ::UVServerAppServer::tyStringSequence& iceP_paReturnName, ::std::string& iceP_paMessage, bool& ret, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseGeneral_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paReturnId);
    istr->read(iceP_paReturnName);
    istr->read(iceP_paMessage);
    istr->read(ret);
    result->_endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::UVServerAppServer::ServerAppServer::_iceI_begin_getFromTableDatbaseByProperty(const ::std::string& iceP_paTableName, const ::std::string& iceP_paStartValue, const ::std::string& iceP_paMaxValue, const ::UVServerAppServer::tyStringSequence& iceP_paProperties, const ::UVServerAppServer::tyStringSequence& iceP_paValue, const ::UVServerAppServer::tyStringSequence& iceP_paTypeValue, const ::UVServerAppServer::tyStringSequence& iceP_paLogExp, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByProperty_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByProperty_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByProperty_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_paTableName);
        ostr->write(iceP_paStartValue);
        ostr->write(iceP_paMaxValue);
        ostr->write(iceP_paProperties);
        ostr->write(iceP_paValue);
        ostr->write(iceP_paTypeValue);
        ostr->write(iceP_paLogExp);
        result->endWriteParams();
        result->invoke(iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByProperty_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::UVServerAppServer::ServerAppServer::end_getFromTableDatbaseByProperty(::UVServerAppServer::tyStringSequence& iceP_paReturnId, ::std::string& iceP_paReturnMessage, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByProperty_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paReturnId);
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

void IceProxy::UVServerAppServer::ServerAppServer::_iceI_end_getFromTableDatbaseByProperty(::UVServerAppServer::tyStringSequence& iceP_paReturnId, ::std::string& iceP_paReturnMessage, bool& ret, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByProperty_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paReturnId);
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::UVServerAppServer::ServerAppServer::_iceI_begin_getFromTableDatbaseByPropertyRepresentProp(const ::std::string& iceP_paTableName, const ::std::string& iceP_paStartValue, const ::std::string& iceP_paMaxValue, const ::UVServerAppServer::tyStringSequence& iceP_paProperties, const ::UVServerAppServer::tyStringSequence& iceP_paValue, const ::UVServerAppServer::tyStringSequence& iceP_paTypeValue, const ::UVServerAppServer::tyStringSequence& iceP_paLogExp, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByPropertyRepresentProp_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByPropertyRepresentProp_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByPropertyRepresentProp_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_paTableName);
        ostr->write(iceP_paStartValue);
        ostr->write(iceP_paMaxValue);
        ostr->write(iceP_paProperties);
        ostr->write(iceP_paValue);
        ostr->write(iceP_paTypeValue);
        ostr->write(iceP_paLogExp);
        result->endWriteParams();
        result->invoke(iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByPropertyRepresentProp_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::UVServerAppServer::ServerAppServer::end_getFromTableDatbaseByPropertyRepresentProp(::UVServerAppServer::tyStringSequence& iceP_paPropertiesReturn, ::UVServerAppServer::tyStringSequence& iceP_paValuesReturn, ::std::string& iceP_paReturnMessage, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByPropertyRepresentProp_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paPropertiesReturn);
    istr->read(iceP_paValuesReturn);
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

void IceProxy::UVServerAppServer::ServerAppServer::_iceI_end_getFromTableDatbaseByPropertyRepresentProp(::UVServerAppServer::tyStringSequence& iceP_paPropertiesReturn, ::UVServerAppServer::tyStringSequence& iceP_paValuesReturn, ::std::string& iceP_paReturnMessage, bool& ret, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_getFromTableDatbaseByPropertyRepresentProp_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paPropertiesReturn);
    istr->read(iceP_paValuesReturn);
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::UVServerAppServer::ServerAppServer::_iceI_begin_getFromTableDatabaseById(const ::std::string& iceP_paTableName, const ::std::string& iceP_paId, const ::UVServerAppServer::tyStringSequence& iceP_paProperties, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseById_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseById_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseById_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_paTableName);
        ostr->write(iceP_paId);
        ostr->write(iceP_paProperties);
        result->endWriteParams();
        result->invoke(iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseById_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::UVServerAppServer::ServerAppServer::end_getFromTableDatabaseById(::UVServerAppServer::tyStringSequence& iceP_paReturnValue, ::std::string& iceP_paReturnMessage, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseById_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paReturnValue);
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

void IceProxy::UVServerAppServer::ServerAppServer::_iceI_end_getFromTableDatabaseById(::UVServerAppServer::tyStringSequence& iceP_paReturnValue, ::std::string& iceP_paReturnMessage, bool& ret, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_getFromTableDatabaseById_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paReturnValue);
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::UVServerAppServer::ServerAppServer::_iceI_begin_getAllTablesFromDatabase(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_getAllTablesFromDatabase_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVServerAppServer_ServerAppServer_getAllTablesFromDatabase_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVServerAppServer_ServerAppServer_getAllTablesFromDatabase_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_UVServerAppServer_ServerAppServer_getAllTablesFromDatabase_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::UVServerAppServer::ServerAppServer::end_getAllTablesFromDatabase(::UVServerAppServer::tyStringSequence& iceP_paTables, ::std::string& iceP_paReturnMessage, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_getAllTablesFromDatabase_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paTables);
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

void IceProxy::UVServerAppServer::ServerAppServer::_iceI_end_getAllTablesFromDatabase(::UVServerAppServer::tyStringSequence& iceP_paTables, ::std::string& iceP_paReturnMessage, bool& ret, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_getAllTablesFromDatabase_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paTables);
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::UVServerAppServer::ServerAppServer::_iceI_begin_getAllMethodsFromTable(const ::std::string& iceP_paTable, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_getAllMethodsFromTable_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVServerAppServer_ServerAppServer_getAllMethodsFromTable_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVServerAppServer_ServerAppServer_getAllMethodsFromTable_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_paTable);
        result->endWriteParams();
        result->invoke(iceC_UVServerAppServer_ServerAppServer_getAllMethodsFromTable_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::UVServerAppServer::ServerAppServer::end_getAllMethodsFromTable(::UVServerAppServer::tyStringSequence& iceP_paMethodName, ::UVServerAppServer::tyStringSequence& iceP_paAlias, ::UVServerAppServer::tyStringSequence& iceP_paSource, ::UVServerAppServer::tyStringSequence& iceP_paSourceName, ::UVServerAppServer::tyStringSequence& iceP_paReturnType, ::std::string& iceP_paReturnMessage, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_getAllMethodsFromTable_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paMethodName);
    istr->read(iceP_paAlias);
    istr->read(iceP_paSource);
    istr->read(iceP_paSourceName);
    istr->read(iceP_paReturnType);
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

void IceProxy::UVServerAppServer::ServerAppServer::_iceI_end_getAllMethodsFromTable(::UVServerAppServer::tyStringSequence& iceP_paMethodName, ::UVServerAppServer::tyStringSequence& iceP_paAlias, ::UVServerAppServer::tyStringSequence& iceP_paSource, ::UVServerAppServer::tyStringSequence& iceP_paSourceName, ::UVServerAppServer::tyStringSequence& iceP_paReturnType, ::std::string& iceP_paReturnMessage, bool& ret, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_getAllMethodsFromTable_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paMethodName);
    istr->read(iceP_paAlias);
    istr->read(iceP_paSource);
    istr->read(iceP_paSourceName);
    istr->read(iceP_paReturnType);
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::UVServerAppServer::ServerAppServer::_iceI_begin_getAllPropertiesFromTable(const ::std::string& iceP_paTable, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_getAllPropertiesFromTable_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVServerAppServer_ServerAppServer_getAllPropertiesFromTable_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVServerAppServer_ServerAppServer_getAllPropertiesFromTable_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_paTable);
        result->endWriteParams();
        result->invoke(iceC_UVServerAppServer_ServerAppServer_getAllPropertiesFromTable_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::UVServerAppServer::ServerAppServer::end_getAllPropertiesFromTable(::UVServerAppServer::tyStringSequence& iceP_paPropertyName, ::UVServerAppServer::tyStringSequence& iceP_paAlias, ::UVServerAppServer::tyStringSequence& iceP_paType, ::UVServerAppServer::tyStringSequence& iceP_paExtra, ::UVServerAppServer::tyStringSequence& iceP_paReference, ::std::string& iceP_paReturnMessage, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_getAllPropertiesFromTable_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paPropertyName);
    istr->read(iceP_paAlias);
    istr->read(iceP_paType);
    istr->read(iceP_paExtra);
    istr->read(iceP_paReference);
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

void IceProxy::UVServerAppServer::ServerAppServer::_iceI_end_getAllPropertiesFromTable(::UVServerAppServer::tyStringSequence& iceP_paPropertyName, ::UVServerAppServer::tyStringSequence& iceP_paAlias, ::UVServerAppServer::tyStringSequence& iceP_paType, ::UVServerAppServer::tyStringSequence& iceP_paExtra, ::UVServerAppServer::tyStringSequence& iceP_paReference, ::std::string& iceP_paReturnMessage, bool& ret, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_getAllPropertiesFromTable_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paPropertyName);
    istr->read(iceP_paAlias);
    istr->read(iceP_paType);
    istr->read(iceP_paExtra);
    istr->read(iceP_paReference);
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::UVServerAppServer::ServerAppServer::_iceI_begin_giveWorkstationClientInfo(const ::std::string& iceP_paWorkstationName, const ::std::string& iceP_paPercentageMemUsage, const ::std::string& iceP_paPercentageDiskUsage, const ::std::string& iceP_paPercentageCpuUsage, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_UVServerAppServer_ServerAppServer_giveWorkstationClientInfo_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVServerAppServer_ServerAppServer_giveWorkstationClientInfo_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVServerAppServer_ServerAppServer_giveWorkstationClientInfo_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_paWorkstationName);
        ostr->write(iceP_paPercentageMemUsage);
        ostr->write(iceP_paPercentageDiskUsage);
        ostr->write(iceP_paPercentageCpuUsage);
        result->endWriteParams();
        result->invoke(iceC_UVServerAppServer_ServerAppServer_giveWorkstationClientInfo_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::UVServerAppServer::ServerAppServer::end_giveWorkstationClientInfo(::std::string& iceP_paReturnMessage, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_giveWorkstationClientInfo_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

void IceProxy::UVServerAppServer::ServerAppServer::_iceI_end_giveWorkstationClientInfo(::std::string& iceP_paReturnMessage, bool& ret, const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVServerAppServer_ServerAppServer_giveWorkstationClientInfo_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(iceP_paReturnMessage);
    istr->read(ret);
    result->_endReadParams();
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::UVServerAppServer::ServerAppServer::_newInstance() const
{
    return new ServerAppServer;
}
/// \endcond

const ::std::string&
IceProxy::UVServerAppServer::ServerAppServer::ice_staticId()
{
    return ::UVServerAppServer::ServerAppServer::ice_staticId();
}

UVServerAppServer::ServerAppServer::~ServerAppServer()
{
}

/// \cond INTERNAL
::Ice::Object* UVServerAppServer::upCast(ServerAppServer* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_UVServerAppServer_ServerAppServer_ids[2] =
{
    "::Ice::Object",
    "::UVServerAppServer::ServerAppServer"
};

}

bool
UVServerAppServer::ServerAppServer::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_UVServerAppServer_ServerAppServer_ids, iceC_UVServerAppServer_ServerAppServer_ids + 2, s);
}

::std::vector< ::std::string>
UVServerAppServer::ServerAppServer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_UVServerAppServer_ServerAppServer_ids[0], &iceC_UVServerAppServer_ServerAppServer_ids[2]);
}

const ::std::string&
UVServerAppServer::ServerAppServer::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
UVServerAppServer::ServerAppServer::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::UVServerAppServer::ServerAppServer";
    return typeId;
#else
    return iceC_UVServerAppServer_ServerAppServer_ids[1];
#endif
}

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_Ping(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->Ping(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_Shutdown(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->Shutdown(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_insertIntoTableDatabase(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_paTableName;
    tyStringSequence iceP_paColumns;
    tyStringSequence iceP_paValue;
    tyStringSequence iceP_paTypeValue;
    istr->read(iceP_paTableName);
    istr->read(iceP_paColumns);
    istr->read(iceP_paValue);
    istr->read(iceP_paTypeValue);
    inS.endReadParams();
    ::std::string iceP_paReturnMessage;
    bool ret = this->insertIntoTableDatabase(iceP_paTableName, iceP_paColumns, iceP_paValue, iceP_paTypeValue, iceP_paReturnMessage, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_paReturnMessage);
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_updateIntoTableDatabase(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_paTableName;
    ::std::string iceP_paId;
    tyStringSequence iceP_paColumns;
    tyStringSequence iceP_paValue;
    tyStringSequence iceP_paTypeValue;
    istr->read(iceP_paTableName);
    istr->read(iceP_paId);
    istr->read(iceP_paColumns);
    istr->read(iceP_paValue);
    istr->read(iceP_paTypeValue);
    inS.endReadParams();
    ::std::string iceP_paReturnMessage;
    bool ret = this->updateIntoTableDatabase(iceP_paTableName, iceP_paId, iceP_paColumns, iceP_paValue, iceP_paTypeValue, iceP_paReturnMessage, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_paReturnMessage);
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_deleteIntoTableDatabase(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_paTableName;
    ::std::string iceP_paId;
    istr->read(iceP_paTableName);
    istr->read(iceP_paId);
    inS.endReadParams();
    ::std::string iceP_paReturnMessage;
    bool ret = this->deleteIntoTableDatabase(iceP_paTableName, iceP_paId, iceP_paReturnMessage, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_paReturnMessage);
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_getFromTableDatabaseGeneral(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_paTableName;
    ::std::string iceP_paStartValue;
    ::std::string iceP_paMaxValue;
    istr->read(iceP_paTableName);
    istr->read(iceP_paStartValue);
    istr->read(iceP_paMaxValue);
    inS.endReadParams();
    tyStringSequence iceP_paReturnId;
    tyStringSequence iceP_paReturnName;
    ::std::string iceP_paMessage;
    bool ret = this->getFromTableDatabaseGeneral(iceP_paTableName, iceP_paStartValue, iceP_paMaxValue, iceP_paReturnId, iceP_paReturnName, iceP_paMessage, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_paReturnId);
    ostr->write(iceP_paReturnName);
    ostr->write(iceP_paMessage);
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_getFromTableDatbaseByProperty(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_paTableName;
    ::std::string iceP_paStartValue;
    ::std::string iceP_paMaxValue;
    tyStringSequence iceP_paProperties;
    tyStringSequence iceP_paValue;
    tyStringSequence iceP_paTypeValue;
    tyStringSequence iceP_paLogExp;
    istr->read(iceP_paTableName);
    istr->read(iceP_paStartValue);
    istr->read(iceP_paMaxValue);
    istr->read(iceP_paProperties);
    istr->read(iceP_paValue);
    istr->read(iceP_paTypeValue);
    istr->read(iceP_paLogExp);
    inS.endReadParams();
    tyStringSequence iceP_paReturnId;
    ::std::string iceP_paReturnMessage;
    bool ret = this->getFromTableDatbaseByProperty(iceP_paTableName, iceP_paStartValue, iceP_paMaxValue, iceP_paProperties, iceP_paValue, iceP_paTypeValue, iceP_paLogExp, iceP_paReturnId, iceP_paReturnMessage, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_paReturnId);
    ostr->write(iceP_paReturnMessage);
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_getFromTableDatbaseByPropertyRepresentProp(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_paTableName;
    ::std::string iceP_paStartValue;
    ::std::string iceP_paMaxValue;
    tyStringSequence iceP_paProperties;
    tyStringSequence iceP_paValue;
    tyStringSequence iceP_paTypeValue;
    tyStringSequence iceP_paLogExp;
    istr->read(iceP_paTableName);
    istr->read(iceP_paStartValue);
    istr->read(iceP_paMaxValue);
    istr->read(iceP_paProperties);
    istr->read(iceP_paValue);
    istr->read(iceP_paTypeValue);
    istr->read(iceP_paLogExp);
    inS.endReadParams();
    tyStringSequence iceP_paPropertiesReturn;
    tyStringSequence iceP_paValuesReturn;
    ::std::string iceP_paReturnMessage;
    bool ret = this->getFromTableDatbaseByPropertyRepresentProp(iceP_paTableName, iceP_paStartValue, iceP_paMaxValue, iceP_paProperties, iceP_paValue, iceP_paTypeValue, iceP_paLogExp, iceP_paPropertiesReturn, iceP_paValuesReturn, iceP_paReturnMessage, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_paPropertiesReturn);
    ostr->write(iceP_paValuesReturn);
    ostr->write(iceP_paReturnMessage);
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_getFromTableDatabaseById(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_paTableName;
    ::std::string iceP_paId;
    tyStringSequence iceP_paProperties;
    istr->read(iceP_paTableName);
    istr->read(iceP_paId);
    istr->read(iceP_paProperties);
    inS.endReadParams();
    tyStringSequence iceP_paReturnValue;
    ::std::string iceP_paReturnMessage;
    bool ret = this->getFromTableDatabaseById(iceP_paTableName, iceP_paId, iceP_paProperties, iceP_paReturnValue, iceP_paReturnMessage, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_paReturnValue);
    ostr->write(iceP_paReturnMessage);
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_getAllTablesFromDatabase(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    tyStringSequence iceP_paTables;
    ::std::string iceP_paReturnMessage;
    bool ret = this->getAllTablesFromDatabase(iceP_paTables, iceP_paReturnMessage, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_paTables);
    ostr->write(iceP_paReturnMessage);
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_getAllMethodsFromTable(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_paTable;
    istr->read(iceP_paTable);
    inS.endReadParams();
    tyStringSequence iceP_paMethodName;
    tyStringSequence iceP_paAlias;
    tyStringSequence iceP_paSource;
    tyStringSequence iceP_paSourceName;
    tyStringSequence iceP_paReturnType;
    ::std::string iceP_paReturnMessage;
    bool ret = this->getAllMethodsFromTable(iceP_paTable, iceP_paMethodName, iceP_paAlias, iceP_paSource, iceP_paSourceName, iceP_paReturnType, iceP_paReturnMessage, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_paMethodName);
    ostr->write(iceP_paAlias);
    ostr->write(iceP_paSource);
    ostr->write(iceP_paSourceName);
    ostr->write(iceP_paReturnType);
    ostr->write(iceP_paReturnMessage);
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_getAllPropertiesFromTable(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_paTable;
    istr->read(iceP_paTable);
    inS.endReadParams();
    tyStringSequence iceP_paPropertyName;
    tyStringSequence iceP_paAlias;
    tyStringSequence iceP_paType;
    tyStringSequence iceP_paExtra;
    tyStringSequence iceP_paReference;
    ::std::string iceP_paReturnMessage;
    bool ret = this->getAllPropertiesFromTable(iceP_paTable, iceP_paPropertyName, iceP_paAlias, iceP_paType, iceP_paExtra, iceP_paReference, iceP_paReturnMessage, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_paPropertyName);
    ostr->write(iceP_paAlias);
    ostr->write(iceP_paType);
    ostr->write(iceP_paExtra);
    ostr->write(iceP_paReference);
    ostr->write(iceP_paReturnMessage);
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceD_giveWorkstationClientInfo(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_paWorkstationName;
    ::std::string iceP_paPercentageMemUsage;
    ::std::string iceP_paPercentageDiskUsage;
    ::std::string iceP_paPercentageCpuUsage;
    istr->read(iceP_paWorkstationName);
    istr->read(iceP_paPercentageMemUsage);
    istr->read(iceP_paPercentageDiskUsage);
    istr->read(iceP_paPercentageCpuUsage);
    inS.endReadParams();
    ::std::string iceP_paReturnMessage;
    bool ret = this->giveWorkstationClientInfo(iceP_paWorkstationName, iceP_paPercentageMemUsage, iceP_paPercentageDiskUsage, iceP_paPercentageCpuUsage, iceP_paReturnMessage, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(iceP_paReturnMessage);
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_UVServerAppServer_ServerAppServer_all[] =
{
    "Ping",
    "Shutdown",
    "deleteIntoTableDatabase",
    "getAllMethodsFromTable",
    "getAllPropertiesFromTable",
    "getAllTablesFromDatabase",
    "getFromTableDatabaseById",
    "getFromTableDatabaseGeneral",
    "getFromTableDatbaseByProperty",
    "getFromTableDatbaseByPropertyRepresentProp",
    "giveWorkstationClientInfo",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "insertIntoTableDatabase",
    "updateIntoTableDatabase"
};

}

/// \cond INTERNAL
bool
UVServerAppServer::ServerAppServer::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_UVServerAppServer_ServerAppServer_all, iceC_UVServerAppServer_ServerAppServer_all + 17, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_UVServerAppServer_ServerAppServer_all)
    {
        case 0:
        {
            return _iceD_Ping(in, current);
        }
        case 1:
        {
            return _iceD_Shutdown(in, current);
        }
        case 2:
        {
            return _iceD_deleteIntoTableDatabase(in, current);
        }
        case 3:
        {
            return _iceD_getAllMethodsFromTable(in, current);
        }
        case 4:
        {
            return _iceD_getAllPropertiesFromTable(in, current);
        }
        case 5:
        {
            return _iceD_getAllTablesFromDatabase(in, current);
        }
        case 6:
        {
            return _iceD_getFromTableDatabaseById(in, current);
        }
        case 7:
        {
            return _iceD_getFromTableDatabaseGeneral(in, current);
        }
        case 8:
        {
            return _iceD_getFromTableDatbaseByProperty(in, current);
        }
        case 9:
        {
            return _iceD_getFromTableDatbaseByPropertyRepresentProp(in, current);
        }
        case 10:
        {
            return _iceD_giveWorkstationClientInfo(in, current);
        }
        case 11:
        {
            return _iceD_ice_id(in, current);
        }
        case 12:
        {
            return _iceD_ice_ids(in, current);
        }
        case 13:
        {
            return _iceD_ice_isA(in, current);
        }
        case 14:
        {
            return _iceD_ice_ping(in, current);
        }
        case 15:
        {
            return _iceD_insertIntoTableDatabase(in, current);
        }
        case 16:
        {
            return _iceD_updateIntoTableDatabase(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
UVServerAppServer::ServerAppServer::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< ServerAppServer, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
UVServerAppServer::ServerAppServer::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< ServerAppServer, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
UVServerAppServer::_icePatchObjectPtr(ServerAppServerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ServerAppServerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(ServerAppServer::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
