//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ICE_LogApplication.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __ICE_LogApplication_h__
#define __ICE_LogApplication_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 10
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace UVLogAppServer
{

class LogAppServer;
class LogAppServerPrx;

}

namespace UVLogAppServer
{

class LogAppServer : public virtual ::Ice::Object
{
public:

    using ProxyType = LogAppServerPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual bool Ping(const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_Ping(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void Shutdown(const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_Shutdown(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void insertItem(::std::string paLogNumber, ::std::string paComputerName, ::std::string paApplicationName, ::std::string paApplicationText, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_insertItem(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace UVLogAppServer
{

class LogAppServerPrx : public virtual ::Ice::Proxy<LogAppServerPrx, ::Ice::ObjectPrx>
{
public:

    bool Ping(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<bool>(true, this, &LogAppServerPrx::_iceI_Ping, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto PingAsync(const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<bool>>().get_future())
    {
        return _makePromiseOutgoing<bool, P>(false, this, &LogAppServerPrx::_iceI_Ping, context);
    }

    ::std::function<void()>
    PingAsync(::std::function<void(bool)> response,
              ::std::function<void(::std::exception_ptr)> ex = nullptr,
              ::std::function<void(bool)> sent = nullptr,
              const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<bool>(std::move(response), std::move(ex), std::move(sent), this, &UVLogAppServer::LogAppServerPrx::_iceI_Ping, context);
    }

    /// \cond INTERNAL
    void _iceI_Ping(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>&, const ::Ice::Context&);
    /// \endcond

    void Shutdown(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &LogAppServerPrx::_iceI_Shutdown, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto ShutdownAsync(const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &LogAppServerPrx::_iceI_Shutdown, context);
    }

    ::std::function<void()>
    ShutdownAsync(::std::function<void()> response,
                  ::std::function<void(::std::exception_ptr)> ex = nullptr,
                  ::std::function<void(bool)> sent = nullptr,
                  const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(std::move(response), std::move(ex), std::move(sent), this, &UVLogAppServer::LogAppServerPrx::_iceI_Shutdown, context);
    }

    /// \cond INTERNAL
    void _iceI_Shutdown(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::Ice::Context&);
    /// \endcond

    void insertItem(const ::std::string& paLogNumber, const ::std::string& paComputerName, const ::std::string& paApplicationName, const ::std::string& paApplicationText, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &LogAppServerPrx::_iceI_insertItem, paLogNumber, paComputerName, paApplicationName, paApplicationText, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto insertItemAsync(const ::std::string& paLogNumber, const ::std::string& paComputerName, const ::std::string& paApplicationName, const ::std::string& paApplicationText, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &LogAppServerPrx::_iceI_insertItem, paLogNumber, paComputerName, paApplicationName, paApplicationText, context);
    }

    ::std::function<void()>
    insertItemAsync(const ::std::string& paLogNumber, const ::std::string& paComputerName, const ::std::string& paApplicationName, const ::std::string& paApplicationText,
                    ::std::function<void()> response,
                    ::std::function<void(::std::exception_ptr)> ex = nullptr,
                    ::std::function<void(bool)> sent = nullptr,
                    const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(std::move(response), std::move(ex), std::move(sent), this, &UVLogAppServer::LogAppServerPrx::_iceI_insertItem, paLogNumber, paComputerName, paApplicationName, paApplicationText, context);
    }

    /// \cond INTERNAL
    void _iceI_insertItem(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    LogAppServerPrx() = default;
    friend ::std::shared_ptr<LogAppServerPrx> IceInternal::createProxy<LogAppServerPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

}
/// \endcond

/// \cond INTERNAL
namespace UVLogAppServer
{

using LogAppServerPtr = ::std::shared_ptr<LogAppServer>;
using LogAppServerPrxPtr = ::std::shared_ptr<LogAppServerPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace UVLogAppServer
{

class LogAppServer;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< LogAppServer>&);
::IceProxy::Ice::Object* upCast(LogAppServer*);
/// \endcond

}

}

namespace UVLogAppServer
{

class LogAppServer;
/// \cond INTERNAL
::Ice::Object* upCast(LogAppServer*);
/// \endcond
typedef ::IceInternal::Handle< LogAppServer> LogAppServerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::UVLogAppServer::LogAppServer> LogAppServerPrx;
typedef LogAppServerPrx LogAppServerPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(LogAppServerPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace UVLogAppServer
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::UVLogAppServer::LogAppServer::begin_Ping.
 * Create a wrapper instance by calling ::UVLogAppServer::newCallback_LogAppServer_Ping.
 */
class Callback_LogAppServer_Ping_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_LogAppServer_Ping_Base> Callback_LogAppServer_PingPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::UVLogAppServer::LogAppServer::begin_Shutdown.
 * Create a wrapper instance by calling ::UVLogAppServer::newCallback_LogAppServer_Shutdown.
 */
class Callback_LogAppServer_Shutdown_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_LogAppServer_Shutdown_Base> Callback_LogAppServer_ShutdownPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::UVLogAppServer::LogAppServer::begin_insertItem.
 * Create a wrapper instance by calling ::UVLogAppServer::newCallback_LogAppServer_insertItem.
 */
class Callback_LogAppServer_insertItem_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_LogAppServer_insertItem_Base> Callback_LogAppServer_insertItemPtr;

}

namespace IceProxy
{

namespace UVLogAppServer
{

class LogAppServer : public virtual ::Ice::Proxy<LogAppServer, ::IceProxy::Ice::Object>
{
public:

    bool Ping(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_Ping(_iceI_begin_Ping(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_Ping(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_Ping(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Ping(const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_Ping(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_Ping(const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_Ping(context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_Ping(const ::UVLogAppServer::Callback_LogAppServer_PingPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_Ping(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_Ping(const ::Ice::Context& context, const ::UVLogAppServer::Callback_LogAppServer_PingPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_Ping(context, cb, cookie);
    }

    bool end_Ping(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_Ping(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void Shutdown(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_Shutdown(_iceI_begin_Shutdown(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_Shutdown(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_Shutdown(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Shutdown(const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_Shutdown(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_Shutdown(const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_Shutdown(context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_Shutdown(const ::UVLogAppServer::Callback_LogAppServer_ShutdownPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_Shutdown(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_Shutdown(const ::Ice::Context& context, const ::UVLogAppServer::Callback_LogAppServer_ShutdownPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_Shutdown(context, cb, cookie);
    }

    void end_Shutdown(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_Shutdown(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void insertItem(const ::std::string& paLogNumber, const ::std::string& paComputerName, const ::std::string& paApplicationName, const ::std::string& paApplicationText, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_insertItem(_iceI_begin_insertItem(paLogNumber, paComputerName, paApplicationName, paApplicationText, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_insertItem(const ::std::string& paLogNumber, const ::std::string& paComputerName, const ::std::string& paApplicationName, const ::std::string& paApplicationText, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_insertItem(paLogNumber, paComputerName, paApplicationName, paApplicationText, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_insertItem(const ::std::string& paLogNumber, const ::std::string& paComputerName, const ::std::string& paApplicationName, const ::std::string& paApplicationText, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_insertItem(paLogNumber, paComputerName, paApplicationName, paApplicationText, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_insertItem(const ::std::string& paLogNumber, const ::std::string& paComputerName, const ::std::string& paApplicationName, const ::std::string& paApplicationText, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_insertItem(paLogNumber, paComputerName, paApplicationName, paApplicationText, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_insertItem(const ::std::string& paLogNumber, const ::std::string& paComputerName, const ::std::string& paApplicationName, const ::std::string& paApplicationText, const ::UVLogAppServer::Callback_LogAppServer_insertItemPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_insertItem(paLogNumber, paComputerName, paApplicationName, paApplicationText, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_insertItem(const ::std::string& paLogNumber, const ::std::string& paComputerName, const ::std::string& paApplicationName, const ::std::string& paApplicationText, const ::Ice::Context& context, const ::UVLogAppServer::Callback_LogAppServer_insertItemPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_insertItem(paLogNumber, paComputerName, paApplicationName, paApplicationText, context, cb, cookie);
    }

    void end_insertItem(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_insertItem(const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace UVLogAppServer
{

class LogAppServer : public virtual ::Ice::Object
{
public:

    typedef LogAppServerPrx ProxyType;
    typedef LogAppServerPtr PointerType;

    virtual ~LogAppServer();

#ifdef ICE_CPP11_COMPILER
    LogAppServer() = default;
    LogAppServer(const LogAppServer&) = default;
    LogAppServer& operator=(const LogAppServer&) = default;
#endif

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual bool Ping(const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_Ping(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void Shutdown(const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_Shutdown(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void insertItem(const ::std::string& paLogNumber, const ::std::string& paComputerName, const ::std::string& paApplicationName, const ::std::string& paApplicationText, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_insertItem(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const LogAppServer& lhs, const LogAppServer& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const LogAppServer& lhs, const LogAppServer& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

}
/// \endcond

namespace UVLogAppServer
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::UVLogAppServer::LogAppServer::begin_Ping.
 * Create a wrapper instance by calling ::UVLogAppServer::newCallback_LogAppServer_Ping.
 */
template<class T>
class CallbackNC_LogAppServer_Ping : public Callback_LogAppServer_Ping_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_LogAppServer_Ping(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        LogAppServerPrx proxy = LogAppServerPrx::uncheckedCast(result->getProxy());
        bool ret;
        try
        {
            ret = proxy->end_Ping(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_Ping.
 */
template<class T> Callback_LogAppServer_PingPtr
newCallback_LogAppServer_Ping(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LogAppServer_Ping<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_Ping.
 */
template<class T> Callback_LogAppServer_PingPtr
newCallback_LogAppServer_Ping(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LogAppServer_Ping<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::UVLogAppServer::LogAppServer::begin_Ping.
 * Create a wrapper instance by calling ::UVLogAppServer::newCallback_LogAppServer_Ping.
 */
template<class T, typename CT>
class Callback_LogAppServer_Ping : public Callback_LogAppServer_Ping_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_LogAppServer_Ping(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        LogAppServerPrx proxy = LogAppServerPrx::uncheckedCast(result->getProxy());
        bool ret;
        try
        {
            ret = proxy->end_Ping(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_Ping.
 */
template<class T, typename CT> Callback_LogAppServer_PingPtr
newCallback_LogAppServer_Ping(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LogAppServer_Ping<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_Ping.
 */
template<class T, typename CT> Callback_LogAppServer_PingPtr
newCallback_LogAppServer_Ping(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LogAppServer_Ping<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::UVLogAppServer::LogAppServer::begin_Shutdown.
 * Create a wrapper instance by calling ::UVLogAppServer::newCallback_LogAppServer_Shutdown.
 */
template<class T>
class CallbackNC_LogAppServer_Shutdown : public Callback_LogAppServer_Shutdown_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_LogAppServer_Shutdown(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_Shutdown.
 */
template<class T> Callback_LogAppServer_ShutdownPtr
newCallback_LogAppServer_Shutdown(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LogAppServer_Shutdown<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_Shutdown.
 */
template<class T> Callback_LogAppServer_ShutdownPtr
newCallback_LogAppServer_Shutdown(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LogAppServer_Shutdown<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_Shutdown.
 */
template<class T> Callback_LogAppServer_ShutdownPtr
newCallback_LogAppServer_Shutdown(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LogAppServer_Shutdown<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_Shutdown.
 */
template<class T> Callback_LogAppServer_ShutdownPtr
newCallback_LogAppServer_Shutdown(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LogAppServer_Shutdown<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::UVLogAppServer::LogAppServer::begin_Shutdown.
 * Create a wrapper instance by calling ::UVLogAppServer::newCallback_LogAppServer_Shutdown.
 */
template<class T, typename CT>
class Callback_LogAppServer_Shutdown : public Callback_LogAppServer_Shutdown_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_LogAppServer_Shutdown(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_Shutdown.
 */
template<class T, typename CT> Callback_LogAppServer_ShutdownPtr
newCallback_LogAppServer_Shutdown(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LogAppServer_Shutdown<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_Shutdown.
 */
template<class T, typename CT> Callback_LogAppServer_ShutdownPtr
newCallback_LogAppServer_Shutdown(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LogAppServer_Shutdown<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_Shutdown.
 */
template<class T, typename CT> Callback_LogAppServer_ShutdownPtr
newCallback_LogAppServer_Shutdown(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LogAppServer_Shutdown<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_Shutdown.
 */
template<class T, typename CT> Callback_LogAppServer_ShutdownPtr
newCallback_LogAppServer_Shutdown(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LogAppServer_Shutdown<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::UVLogAppServer::LogAppServer::begin_insertItem.
 * Create a wrapper instance by calling ::UVLogAppServer::newCallback_LogAppServer_insertItem.
 */
template<class T>
class CallbackNC_LogAppServer_insertItem : public Callback_LogAppServer_insertItem_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_LogAppServer_insertItem(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_insertItem.
 */
template<class T> Callback_LogAppServer_insertItemPtr
newCallback_LogAppServer_insertItem(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LogAppServer_insertItem<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_insertItem.
 */
template<class T> Callback_LogAppServer_insertItemPtr
newCallback_LogAppServer_insertItem(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LogAppServer_insertItem<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_insertItem.
 */
template<class T> Callback_LogAppServer_insertItemPtr
newCallback_LogAppServer_insertItem(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LogAppServer_insertItem<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_insertItem.
 */
template<class T> Callback_LogAppServer_insertItemPtr
newCallback_LogAppServer_insertItem(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_LogAppServer_insertItem<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::UVLogAppServer::LogAppServer::begin_insertItem.
 * Create a wrapper instance by calling ::UVLogAppServer::newCallback_LogAppServer_insertItem.
 */
template<class T, typename CT>
class Callback_LogAppServer_insertItem : public Callback_LogAppServer_insertItem_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_LogAppServer_insertItem(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_insertItem.
 */
template<class T, typename CT> Callback_LogAppServer_insertItemPtr
newCallback_LogAppServer_insertItem(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LogAppServer_insertItem<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_insertItem.
 */
template<class T, typename CT> Callback_LogAppServer_insertItemPtr
newCallback_LogAppServer_insertItem(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LogAppServer_insertItem<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_insertItem.
 */
template<class T, typename CT> Callback_LogAppServer_insertItemPtr
newCallback_LogAppServer_insertItem(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LogAppServer_insertItem<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::UVLogAppServer::LogAppServer::begin_insertItem.
 */
template<class T, typename CT> Callback_LogAppServer_insertItemPtr
newCallback_LogAppServer_insertItem(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_LogAppServer_insertItem<T, CT>(instance, 0, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
