//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ICE_LogApplication.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <ICE_LogApplication.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 10
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_UVLogAppServer_LogAppServer_ids[2] =
{
    "::Ice::Object",
    "::UVLogAppServer::LogAppServer"
};
const ::std::string iceC_UVLogAppServer_LogAppServer_ops[] =
{
    "Ping",
    "Shutdown",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "insertItem"
};
const ::std::string iceC_UVLogAppServer_LogAppServer_Ping_name = "Ping";
const ::std::string iceC_UVLogAppServer_LogAppServer_Shutdown_name = "Shutdown";
const ::std::string iceC_UVLogAppServer_LogAppServer_insertItem_name = "insertItem";

}

bool
UVLogAppServer::LogAppServer::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_UVLogAppServer_LogAppServer_ids, iceC_UVLogAppServer_LogAppServer_ids + 2, s);
}

::std::vector<::std::string>
UVLogAppServer::LogAppServer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_UVLogAppServer_LogAppServer_ids[0], &iceC_UVLogAppServer_LogAppServer_ids[2]);
}

::std::string
UVLogAppServer::LogAppServer::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
UVLogAppServer::LogAppServer::ice_staticId()
{
    static const ::std::string typeId = "::UVLogAppServer::LogAppServer";
    return typeId;
}

/// \cond INTERNAL
bool
UVLogAppServer::LogAppServer::_iceD_Ping(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->Ping(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVLogAppServer::LogAppServer::_iceD_Shutdown(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->Shutdown(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVLogAppServer::LogAppServer::_iceD_insertItem(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_paLogNumber;
    ::std::string iceP_paComputerName;
    ::std::string iceP_paApplicationName;
    ::std::string iceP_paApplicationText;
    istr->readAll(iceP_paLogNumber, iceP_paComputerName, iceP_paApplicationName, iceP_paApplicationText);
    inS.endReadParams();
    this->insertItem(::std::move(iceP_paLogNumber), ::std::move(iceP_paComputerName), ::std::move(iceP_paApplicationName), ::std::move(iceP_paApplicationText), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVLogAppServer::LogAppServer::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_UVLogAppServer_LogAppServer_ops, iceC_UVLogAppServer_LogAppServer_ops + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_UVLogAppServer_LogAppServer_ops)
    {
        case 0:
        {
            return _iceD_Ping(in, current);
        }
        case 1:
        {
            return _iceD_Shutdown(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        case 6:
        {
            return _iceD_insertItem(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
UVLogAppServer::LogAppServerPrx::_iceI_Ping(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_UVLogAppServer_LogAppServer_Ping_name);
    outAsync->invoke(iceC_UVLogAppServer_LogAppServer_Ping_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
UVLogAppServer::LogAppServerPrx::_iceI_Shutdown(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_UVLogAppServer_LogAppServer_Shutdown_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
UVLogAppServer::LogAppServerPrx::_iceI_insertItem(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_paLogNumber, const ::std::string& iceP_paComputerName, const ::std::string& iceP_paApplicationName, const ::std::string& iceP_paApplicationText, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_UVLogAppServer_LogAppServer_insertItem_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_paLogNumber, iceP_paComputerName, iceP_paApplicationName, iceP_paApplicationText);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
UVLogAppServer::LogAppServerPrx::_newInstance() const
{
    return ::IceInternal::createProxy<LogAppServerPrx>();
}
/// \endcond

const ::std::string&
UVLogAppServer::LogAppServerPrx::ice_staticId()
{
    return LogAppServer::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_UVLogAppServer_LogAppServer_Ping_name = "Ping";

const ::std::string iceC_UVLogAppServer_LogAppServer_Shutdown_name = "Shutdown";

const ::std::string iceC_UVLogAppServer_LogAppServer_insertItem_name = "insertItem";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::UVLogAppServer::upCast(LogAppServer* p) { return p; }

void
::IceProxy::UVLogAppServer::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< LogAppServer>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new LogAppServer;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::UVLogAppServer::LogAppServer::_iceI_begin_Ping(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_UVLogAppServer_LogAppServer_Ping_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVLogAppServer_LogAppServer_Ping_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVLogAppServer_LogAppServer_Ping_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_UVLogAppServer_LogAppServer_Ping_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::UVLogAppServer::LogAppServer::end_Ping(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UVLogAppServer_LogAppServer_Ping_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::UVLogAppServer::LogAppServer::_iceI_begin_Shutdown(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVLogAppServer_LogAppServer_Shutdown_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVLogAppServer_LogAppServer_Shutdown_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_UVLogAppServer_LogAppServer_Shutdown_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::UVLogAppServer::LogAppServer::end_Shutdown(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_UVLogAppServer_LogAppServer_Shutdown_name);
}

::Ice::AsyncResultPtr
IceProxy::UVLogAppServer::LogAppServer::_iceI_begin_insertItem(const ::std::string& iceP_paLogNumber, const ::std::string& iceP_paComputerName, const ::std::string& iceP_paApplicationName, const ::std::string& iceP_paApplicationText, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UVLogAppServer_LogAppServer_insertItem_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UVLogAppServer_LogAppServer_insertItem_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_paLogNumber);
        ostr->write(iceP_paComputerName);
        ostr->write(iceP_paApplicationName);
        ostr->write(iceP_paApplicationText);
        result->endWriteParams();
        result->invoke(iceC_UVLogAppServer_LogAppServer_insertItem_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::UVLogAppServer::LogAppServer::end_insertItem(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_UVLogAppServer_LogAppServer_insertItem_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::UVLogAppServer::LogAppServer::_newInstance() const
{
    return new LogAppServer;
}
/// \endcond

const ::std::string&
IceProxy::UVLogAppServer::LogAppServer::ice_staticId()
{
    return ::UVLogAppServer::LogAppServer::ice_staticId();
}

UVLogAppServer::LogAppServer::~LogAppServer()
{
}

/// \cond INTERNAL
::Ice::Object* UVLogAppServer::upCast(LogAppServer* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_UVLogAppServer_LogAppServer_ids[2] =
{
    "::Ice::Object",
    "::UVLogAppServer::LogAppServer"
};

}

bool
UVLogAppServer::LogAppServer::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_UVLogAppServer_LogAppServer_ids, iceC_UVLogAppServer_LogAppServer_ids + 2, s);
}

::std::vector< ::std::string>
UVLogAppServer::LogAppServer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_UVLogAppServer_LogAppServer_ids[0], &iceC_UVLogAppServer_LogAppServer_ids[2]);
}

const ::std::string&
UVLogAppServer::LogAppServer::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
UVLogAppServer::LogAppServer::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::UVLogAppServer::LogAppServer";
    return typeId;
#else
    return iceC_UVLogAppServer_LogAppServer_ids[1];
#endif
}

/// \cond INTERNAL
bool
UVLogAppServer::LogAppServer::_iceD_Ping(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->Ping(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVLogAppServer::LogAppServer::_iceD_Shutdown(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->Shutdown(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
UVLogAppServer::LogAppServer::_iceD_insertItem(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_paLogNumber;
    ::std::string iceP_paComputerName;
    ::std::string iceP_paApplicationName;
    ::std::string iceP_paApplicationText;
    istr->read(iceP_paLogNumber);
    istr->read(iceP_paComputerName);
    istr->read(iceP_paApplicationName);
    istr->read(iceP_paApplicationText);
    inS.endReadParams();
    this->insertItem(iceP_paLogNumber, iceP_paComputerName, iceP_paApplicationName, iceP_paApplicationText, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_UVLogAppServer_LogAppServer_all[] =
{
    "Ping",
    "Shutdown",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "insertItem"
};

}

/// \cond INTERNAL
bool
UVLogAppServer::LogAppServer::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_UVLogAppServer_LogAppServer_all, iceC_UVLogAppServer_LogAppServer_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_UVLogAppServer_LogAppServer_all)
    {
        case 0:
        {
            return _iceD_Ping(in, current);
        }
        case 1:
        {
            return _iceD_Shutdown(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        case 6:
        {
            return _iceD_insertItem(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
UVLogAppServer::LogAppServer::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< LogAppServer, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
UVLogAppServer::LogAppServer::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< LogAppServer, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
UVLogAppServer::_icePatchObjectPtr(LogAppServerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = LogAppServerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(LogAppServer::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
